### ISSUE TITLE
Combat tracker improvements

### ISSUE THREAD

**Issue by Miravalier** [Miravalier/NonsensePage#22]
- [x] Put a message in the chat for end turn, whisper players for "up next"
- [x] Don't render the end turn button when it's not that player's turn (always render for GM)
- [X] Add a sort by initiative button to the combat tracker for the GM
- [X] When an update {$rotate: <some_combatant_id>} comes in on the subscription, just move the combatant div with that id to the end of the list instead of reloading
